# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from supiro_lite/motorpower.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class motorpower(genpy.Message):
  _md5sum = "0ec0221cf467c083d5f32af96e0b92dc"
  _type = "supiro_lite/motorpower"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 leftpwr
int16 rightpwr
int16 leftdir
int16 rightdir
"""
  __slots__ = ['leftpwr','rightpwr','leftdir','rightdir']
  _slot_types = ['int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       leftpwr,rightpwr,leftdir,rightdir

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(motorpower, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.leftpwr is None:
        self.leftpwr = 0
      if self.rightpwr is None:
        self.rightpwr = 0
      if self.leftdir is None:
        self.leftdir = 0
      if self.rightdir is None:
        self.rightdir = 0
    else:
      self.leftpwr = 0
      self.rightpwr = 0
      self.leftdir = 0
      self.rightdir = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4h().pack(_x.leftpwr, _x.rightpwr, _x.leftdir, _x.rightdir))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.leftpwr, _x.rightpwr, _x.leftdir, _x.rightdir,) = _get_struct_4h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4h().pack(_x.leftpwr, _x.rightpwr, _x.leftdir, _x.rightdir))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.leftpwr, _x.rightpwr, _x.leftdir, _x.rightdir,) = _get_struct_4h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4h = None
def _get_struct_4h():
    global _struct_4h
    if _struct_4h is None:
        _struct_4h = struct.Struct("<4h")
    return _struct_4h
